from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pandas as pd
import streamlit as st

BASE_DIR = Path(__file__).resolve().parents[1]
CONFIG_PATH = BASE_DIR / "config" / "settings.json"


@st.cache_data(show_spinner=False)
def load_config() -> dict[str, Any]:
    """Load dashboard configuration so thresholds and assumptions are not hard-coded in pages."""
    with CONFIG_PATH.open("r", encoding="utf-8") as file:
        return json.load(file)


@st.cache_data(show_spinner="Loading scored credit portfolio...")
def load_portfolio() -> pd.DataFrame:
    """Load the dashboard-ready scored portfolio and apply lightweight type fixes."""
    config = load_config()
    path = BASE_DIR / config["data_path"]
    if not path.exists():
        raise FileNotFoundError(
            f"Scored portfolio not found at {path}. Place scored_portfolio.csv in the data folder."
        )
    df = pd.read_csv(path)
    numeric_columns = [
        "loan_amnt", "term_months", "int_rate_decimal", "predicted_pd", "lgd", "ead",
        "expected_loss", "expected_interest_income", "funding_cost", "operating_cost",
        "expected_profit", "expected_return_pct", "annual_inc", "dti", "delinq_2yrs",
        "inq_last_6mths", "open_acc", "total_acc", "revol_bal", "revol_util", "mort_acc",
        "pub_rec", "pub_rec_bankruptcies",
    ]
    for column in numeric_columns:
        if column in df.columns:
            df[column] = pd.to_numeric(df[column], errors="coerce")
    if "borrower_id" not in df.columns:
        df.insert(0, "borrower_id", [f"LC-{idx + 1:07d}" for idx in range(len(df))])
    return df


@st.cache_data(show_spinner=False)
def load_report(file_name: str) -> pd.DataFrame:
    """Load a CSV report generated by the modelling or EDA pipeline."""
    path = BASE_DIR / "reports" / file_name
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


@st.cache_data(show_spinner=False)
def load_markdown_report(file_name: str) -> str:
    """Load a markdown report for the reports page."""
    path = BASE_DIR / "reports" / file_name
    return path.read_text(encoding="utf-8") if path.exists() else ""


def get_plot_path(file_name: str) -> Path:
    """Return a plot path without assuming the image exists."""
    return BASE_DIR / "plots" / file_name
