from __future__ import annotations

from io import BytesIO

import pandas as pd

from services.risk_engine import top_reason_codes


def borrower_credit_memo(row: pd.Series) -> str:
    """Generate a plain-language credit memo for export."""
    risk_drivers, mitigants = top_reason_codes(row)
    drivers = "\n".join(f"- {item}" for item in risk_drivers) or "- No material adverse driver detected from available fields."
    strengths = "\n".join(f"- {item}" for item in mitigants) or "- No material mitigant detected from available fields."
    return f"""
# Borrower Credit Memo

**Borrower ID:** {row.get('borrower_id', 'N/A')}  
**Facility:** {row.get('facility_type', 'N/A')}  
**Tenor:** {row.get('term_months', 'N/A')} months  
**Loan Amount:** ${float(row.get('loan_amnt', 0)):,.0f}  
**Predicted PD:** {float(row.get('predicted_pd', 0)):.2%}  
**Risk Band:** {row.get('risk_band', 'N/A')}  
**Expected Loss:** ${float(row.get('expected_loss', 0)):,.0f}  
**Expected Return:** {float(row.get('expected_return_pct', 0)):.2%}  
**Recommended Decision:** {row.get('recommended_decision', 'N/A')}  

## Key Risk Drivers
{drivers}

## Key Mitigants
{strengths}

## Analyst Note
This memo is generated by the Retail Credit Intelligence prototype. It supports decision review but does not replace policy approval, documentation checks, fraud controls, KYC/AML, or delegated credit authority.
""".strip()


def dataframe_to_excel_bytes(df: pd.DataFrame, sheet_name: str = "Portfolio") -> bytes:
    """Convert a dataframe to Excel bytes for Streamlit download buttons."""
    output = BytesIO()
    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        df.to_excel(writer, sheet_name=sheet_name, index=False)
    return output.getvalue()
